source "https://rubygems.org"

gem "activerecord", "~> 5.0", require: "active_record"
gem "pg", "0.21.0"
gem "rake", "~> 12.0"

gem "rspec", "~> 3.0"
gem "factory_bot", "~> 4.0"
gem "shoulda-matchers", "~> 3.0"
gem "database_cleaner", "~> 1.0"
gem "pry-byebug", "~> 3.5.0"
